# Generated by Django 4.2.7 on 2023-11-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatmug_app', '0002_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the vendor acknowledged the PO.', null=True),
        ),
    ]
